### ISSUE TITLE
Support units

### ISSUE THREAD

**Issue by cstjean** [mschauer/GaussianDistributions.jl#14]
We started using units everywhere in our code, and it would be nice to have them inside GaussianDistributions too:

```julia
julia> using Unitful, GaussianDistributions

julia> rand(Gaussian(1.0u"m", 1.0u"m^2"))
ERROR: MethodError: no method matching randn(::Random.MersenneTwister, ::Type{Quantity{Float64,Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)},Unitful.FreeUnits{(Unitful.Unit{:Meter,Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)}}}})
Closest candidates are:
  randn(::Random.AbstractRNG, ::Type{T}, ::Tuple{Vararg{Int64,N}} where N) where T at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Random/src/normal.jl:179
  randn(::Random.AbstractRNG, ::Type{T}, ::Integer, ::Integer...) where T at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Random/src/normal.jl:182
  randn(::Random.AbstractRNG) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Random/src/normal.jl:37
  ...
Stacktrace:
 [1] randn(::Type{Quantity{Float64,Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)},Unitful.FreeUnits{(Unitful.Unit{:Meter,Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)}}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Random/src/normal.jl:166
```

The current definition is `rand(P::Gaussian{<:Number}) = P.μ + randn(typeof(P.μ)) * sqrt(P.Σ)`. I believe the easiest way to do this would be to add `Base.randn(::Quantity{T}) = randn(T)` to Unitful.jl. Then GaussianDistrubtions wouldn't have to import Unitful.

@ajkeller34 what do you think? Initially, I felt like `randn(typeof(u"1.0m"))` should return a quantity in meter. That would match the randn docstring

>   Generate a normally-distributed random number of type T with mean 0 and standard deviation 1.

However, `P.μ + randn(typeof(P.μ)) * sqrt(P.Σ)` is pretty fundamental, and it expects `randn(typeof(u"1.0m"))` to be dimensionless, which makes sense in some ways, too.

**Comment by mschauer** [comment]
Ah, that is interesting. Could we do 
```
P.μ + randn(typeof(one(P.μ))) * sqrt(P.Σ)
```
instead?

**Comment by mschauer** [comment]
PS: I think it would be very important to support units to live up to the claim that our `Gaussian`s can represent uncertainty.

**Comment by cstjean** [comment]
That's a great idea!

**Comment by ajkeller34** [comment]
Yes, that's a good approach. I'm hesitant to implement `randn` on quantity types because probably `randn(typeof(x))` is a pretty common thing people do and the distribution of outputs would not be invariant under unit conversions of the input `x`. Most operations on unitful quantities do not yield different physical quantities depending on input units.

**Comment by mschauer** [comment]
Do you or should I?

**Comment by cstjean** [comment]
You can if you want? For my application, it's a marginal use case. My big question mark is how to do Kalman filtering when the components of the hidden state have different units. Then the transition matrix also needs to have different units on each row. It seems doable with tuples of units, but it's not obvious what the best design is.

**Comment by mschauer** [comment]
> Kalman filtering when the components of the hidden state have different units.

Prize question! If I recall correctly, Units.jl is not well suited for this task, because arrays cannot contain values of different units in a type stable way. I figured that it would necessitate a completely new way to deal with vectors of mixed units, something out of scope for me.

**Comment by ajkeller34** [comment]
The way I would approach this would be to define arrays with custom broadcasting, provided your arrays are structured enough. Broadcasting can be made type stable even if indexing cannot, provided there is some way to declare which parts of the array have the same type. For example, given a [stress-energy tensor](https://en.wikipedia.org/wiki/Stress–energy_tensor) you know which parts of the matrix should have the same units, you could have a matrix type built out of four type-stable smaller arrays, and then you could define broadcasting operations as appropriate. This would probably be best developed in a new package since it wouldn't depend on Unitful at all.

**Comment by mschauer** [comment]
Now that you say this, I have almost implemented that for maybe the most useful case of Vectors in Hamiltonian systems: https://gist.github.com/mschauer/a8273687cd514d3c0a06e518978634df
With small changes you could allow different units there.

**Comment by cstjean** [comment]
It seems that `logpdf(Gaussian(1.0u"m", 1.0u"m^2"))` cannot be defined, because the `pdf` is in units of `m^-1`, thus one cannot take the log. 

And... if the `pdf` of a Gaussian is in `1/m`, then so is the likelihood at each step of a kalman filter. And so the cumulative likelihood after 100 steps is in units of `1/m^100`???? Am I missing something? It makes some sense (only likelihood ratios are meaningful), but if it's true, that really sucks for unitful Kalman filtering :cry:

**Comment by mschauer** [comment]
This must have an answer.

**Comment by mschauer** [comment]
... and of course it has. The background is that a density is aways defined with respect to the reference measure and the reference measure here is derived from the size of intervals which is unitful. Integrating the density which really has a 1/m unit with respect to the reference measure the units cancel and you get a probability, a unitless quantity. Taking the log of a unitful quantity is not supported by Unitful (you get an additive log unit instead of a normal multiplicative unit, but that is something the Unitful people can think about). In the meantime we can just give the likelihood with respect to the unitless reference measure (by multiplying with `oneunit`). The only drawback is that likelihoods between filters under a change of unit become incomparable, but I'd be surprised if people would rely on that. :-)

**Comment by cstjean** [comment]
`log` units wouldn't solve the fundamental problem, which is that the unit of the cumulative likelihood changes after each step (by a factor of `1/m`). As long as the unit is stored in the type system, this behaviour is a non-starter for performance AFAIK.

We can always strip the units and add them back later of course, but I was hoping for an elegant solution.

**Comment by mschauer** [comment]
The log likelihood changes by an additional `+1logunit`, so at the end `+100logunits` which can be done with good performance, but is not implemented. Lets strip the unit.

**Comment by cstjean** [comment]
> you could have a matrix type built out of four type-stable smaller arrays,

@ajkeller34 I'm not a master of linear algebra, but wouldn't operations like computing the inverse be quite slow/painful to implement given this approach?

I'm thinking of defining a `m::UnitfulMatrix` type that wraps a regular `Matrix{Float64}`, where the unit of `m[i,j]` is `m.row_units[i] * m.col_units[j]`. It seems like it would line up better with linear algebra operations (eg. it can represent a covariance matrix).

**Comment by ajkeller34** [comment]
When it comes to numerical implementations of linear algebra, I'm no expert either... kind of just thinking out loud. Probably the best implementation may depend on exactly what you're doing. Suppose you wanted to add two unitful matrices. If you have to look up the units of each entry, as you would by keeping abstractly-typed `row_units` and `col_units` vectors, then you're doing dynamic dispatch when you add each entry `A[i,j] + B[i,j]`. On the other hand, if you have concretely typed blocks in your matrices, then at least you maintain type stability when adding each block, and this can be done efficiently. I have not thought through all of the linear algebra operations and identified which ones would be good/bad with this approach.

**Comment by cstjean** [comment]
>  as you would by keeping abstractly-typed row_units and col_units vectors

Right - I would use a definition like

```julia
struct UnitfulArray{N, T<:AbstractArray{N}, U<:NTuple{N, Tuple}} <: AbstractArray{N, Quantity}
    arr::T
    units::U
end
```

where `units` is a tuple of tuple of `Units`, like `((u"m", u"s"), (NoUnits, NoUnits))`. So matrix-matrix operations can be made type-stable, and incur no runtime penalty.

**Comment by cstjean** [comment]
The nice thing about this approach, too, is that for some units `r1, r2, c1, c2`, the object `u = UnitfulArray(mat, ((r1, r2), (c1, c2)))` is mathematically equivalent to `Diagonal([r1, r2]) * mat * Diagonal([c1, c2])`. From there, it's clear how matrix inversion, transpose, etc. should be handled.

**Comment by ajkeller34** [comment]
Ah yes, I think a tuple would work. Would you be interested in making a PR to Unitful at some point? (It is a great idea, I'm just not sure I have the bandwidth to implement it at the moment!)

**Comment by cstjean** [comment]
@mschauer I've come around to agreeing with your proposal for log units. Something like:

```julia
ll = LogQuantity{typeof(m)}[2.33-log(m), 4.52-2*log(m), 6.42-3*log(m), ...]
```

Weird! It should be efficient, at least. The only terrible operation would be `exp.(ll)`, which would generate `length(ll)` new types (`m^-1, m^-2, ...`) But presumably one would never need that, or could simply do `exp.(ustrip.(ll))`

@ajkeller34 Any thought? Sorry - we're stretching unitful a lot it seems.

EDIT: I'm not necessarily suggesting adding this to Unitful.jl. It would mess Unitful's chi to have units which are not encoded in the type system.

**Comment by cstjean** [comment]
Not sure what changed but 

```julia
julia> rand(Gaussian(100.0u"m", 1.0u"m^2"))
98.86269855619292 m
```

This works now. I'll close this issue, as it has meandered a bit.
