### ISSUE TITLE
Does not support integer means

### ISSUE THREAD

**Issue by cstjean** [mschauer/GaussianDistributions.jl#5]
`randn(Int)` is not defined, so integer means are broken. We should probably convert the means to... `AbstractFloat`?

```julia
julia> using GaussianDistributions
INFO: Recompiling stale cache file /home/cst-jean/.julia/lib/v0.6/GaussianDistributions.ji for module GaussianDistributions.

julia> rand(Gaussian(1, 1.0))
ERROR: MethodError: no method matching randn(::MersenneTwister, ::Type{Int64})
Closest candidates are:
  randn(::AbstractRNG, ::Type{T}, ::Tuple{Vararg{Int64,N}} where N) where T at random.jl:1387
  randn(::AbstractRNG, ::Type{T}, ::Integer, ::Integer...) where T at random.jl:1389
  randn(::AbstractRNG) at random.jl:1257
```

**Comment by mschauer** [comment]
I am not sure: `Int`-means are not possible *because* no method matches `randn(::MersenneTwister, ::Type{Int64})`. I have the impression that this is actually a helpful way to fail.

**Comment by cstjean** [comment]
Well, there's no `randn(::Type{Int64})` because there is no normally distributed set of integer. But a Gaussian of integer mean and variance seems reasonable to me. `rand(Distributions.Normal(1,2))` works, in any case...
