### ISSUE TITLE
Multiplication and addition by matrix

### ISSUE THREAD

**Issue by cstjean** [mschauer/GaussianDistributions.jl#6]
I'm looking at the Kalman code... Since affine transforms can be applied to Gaussians, wouldn't it be neat if `*(::Gaussian, M::Matrix)` transformed it according to the same equations as in Kalman.jl?

```julia
function predict!(s, x, P, t, M::LinearHomogSystem)
    x = evolve(s, x, P, t, M)
    Ppred = M.Phi*P*M.Phi' + M.Q
    x, Ppred, M.Phi
end

function evolve(s, x, P, t, M::LinearHomogSystem)
    M.Phi*x + M.b
end
```

After all, a distribution is a set of points, and multiplying each point P by M yields the gaussian with mean/cov described by `(x, Ppred)`

**Comment by cstjean** [comment]
Something like

```julia
Base.:+(g::Gaussian, vec::AbstractVector) = Gaussian(g.μ + vec, g.Σ)
Base.:*(M::AbstractMatrix, g::Gaussian) = Gaussian(M * g.μ, M * g.Σ * M')
```

**Comment by mschauer** [comment]
Nice idea!

**Comment by cstjean** [comment]
Working on the PR. Does it make sense to support `g * M`? If each point in a Gaussian is a column vector, then... no?

**Comment by mschauer** [comment]
Left multiplication should be enough

**Comment by cstjean** [comment]
Fixed by #8

**Comment by cstjean** [comment]
Along the same lines, how about `+(g1::Gaussian, g2::Gaussian) = Gaussian(mean(g1)+mean(g2), cov(g1)+cov(g2)`?

**Comment by mschauer** [comment]
As that only holds for independence I would leave it out.

**Comment by cstjean** [comment]
Good point.
