### ISSUE TITLE
dim vs. ndims

### ISSUE THREAD

**Issue by cstjean** [mschauer/GaussianDistributions.jl#7]
Base has

```julia
> ?ndims
ndims(A::AbstractArray) -> Integer

Returns the number of dimensions of A.

julia> A = ones(3,4,5);

julia> ndims(A)
3
```

I'm not 100% positive on this, but shouldn't we replace `dim(P::Gaussian) = length(P.μ)` by `ndims(...) = ...`?

**Comment by mschauer** [comment]
I decided against it because Gaussian does not implement the array protocol.

**Comment by cstjean** [comment]
Ok.
